version = 1

test_patterns = [
  "tests/**",
]

exclude_patterns = [
  "dist/**",
  "android/**",
  "ios/**",
  "node_modules/**",
  "coverage/**",
  "*.config.ts",
  "*.config.js",
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  runtime_version = 24
  "no-var" = "off"
  "eqeqeq" = "off"
  "prefer-arrow-callback" = "off"
  "no-empty" = "off"

[[analyzers]]
name = "shell"
enabled = true
