version = 1

test_patterns = [
  'tests/**',
]

exclude_patterns = [
  'dist/**',
  'android/**',
  'ios/**',
  'node_modules/**',
  'coverage/**',
  '*.config.ts',
  '*.config.js',
]

[[analyzers]]
name = 'javascript'
enabled = true

  [analyzers.meta]
  runtime_version = 24

  [[analyzers.linters]]
  name = 'eslint'
  enabled = true

[[analyzers]]
name = 'shell'
enabled = true