[default]
extends = "default"

[MD013]
line_length = 240

[MD024]
allow_different_nesting = true

[MD060]
enabled = false

[MD031]
enabled = false

[MD041]
enabled = false

[MD032]
enabled = false

[MD033]
enabled = false
